# Generated by Django 4.0.2 on 2022-03-11 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentation', '0006_remove_tenant_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Введите ФИО', max_length=200)),
                ('contact_details', models.CharField(help_text='Введите контактные данные', max_length=200)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation.apartment')),
            ],
        ),
    ]
