# Generated by Django 4.0.2 on 2022-04-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0010_remove_equipment_cost_remove_equipment_quantity_and_more'),
        ('users', '0005_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.apartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.position'),
            preserve_default=False,
        ),
    ]
