# Generated by Django 4.0.2 on 2022-05-06 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentation', '0016_alter_annualplan_options_alter_apartment_options_and_more'),
        ('users', '0006_alter_tenant_apartment_alter_worker_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'жильца', 'verbose_name_plural': 'Жильцы'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'работника', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.apartment', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_details',
            field=models.CharField(max_length=200, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='contact_details',
            field=models.CharField(max_length=200, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
