# Generated by Django 4.0.2 on 2022-02-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_equipment_servicetype_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='equipment',
            field=models.ManyToManyField(to='documentation.Equipment'),
        ),
    ]
