# Generated by Django 4.0.2 on 2022-02-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_service_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='title',
            field=models.CharField(help_text='Введите наименование оборудования', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Введите название услуги', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='title',
            field=models.CharField(help_text='Введите тип услуги', max_length=200),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_details',
            field=models.CharField(help_text='Введите контактные данные', max_length=200),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(help_text='Введите ФИО', max_length=200),
        ),
    ]
