# Generated by Django 4.0.2 on 2022-03-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_alter_equipment_title_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(help_text='Введите название улицы', max_length=200),
        ),
    ]
