# Generated by Django 4.0.2 on 2022-03-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_remove_tenant_apartment'),
        ('requests', '0005_alter_comment_tenant_alter_repairrequest_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
