# Generated by Django 4.0.2 on 2022-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0008_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='service_type',
        ),
        migrations.AddField(
            model_name='position',
            name='service_type',
            field=models.ManyToManyField(to='documentation.ServiceType'),
        ),
    ]
