# Generated by Django 4.0.2 on 2022-04-20 13:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_worker'),
        ('documentation', '0009_remove_position_service_type_position_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.building'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='street',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.street'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentation.servicetype'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='Запланирована', max_length=200)),
                ('start_time', models.TimeField(default=datetime.time(8, 0))),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.building')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.worker')),
            ],
        ),
    ]
