# Generated by Django 4.0.2 on 2022-04-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0010_remove_equipment_cost_remove_equipment_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='nature',
            field=models.CharField(choices=[('Заявка', 'Заявка'), ('Замечание', 'Замечание'), ('Уборка', 'Уборка'), ('Ремонт', 'Ремонт'), ('Благоустройство', 'Благоустройство')], default='Замечание', max_length=20),
        ),
    ]
