# Generated by Django 4.0.2 on 2022-04-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_tenant_apartment_alter_worker_position'),
        ('documentation', '0012_improvementplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvementplan',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.worker'),
        ),
    ]
