# Generated by Django 4.0.2 on 2022-05-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0016_alter_annualplan_options_alter_apartment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualplan',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='building',
            name='number',
            field=models.IntegerField(verbose_name='Номер здания'),
        ),
    ]
