# Generated by Django 4.0.2 on 2022-03-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_alter_street_name'),
        ('requests', '0002_repairrequest_end_time_repairrequest_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(help_text='Введите комментарий', max_length=200)),
                ('status', models.CharField(default='На рассмотрении', help_text='Введите статус заявки', max_length=200)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.repairrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(help_text='Введите комментарий', max_length=200)),
                ('status', models.CharField(default='На рассмотрении', help_text='Введите статус заявки', max_length=200)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation.service')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation.tenant')),
            ],
        ),
    ]
