# Generated by Django 4.0.2 on 2022-04-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_rename_repairrequest_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('В обработке', 'В обработке'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена'), ('Отложена', 'Отложена'), ('В процессе', 'В процессе'), ('Выполнена', 'Выполнена')], default='На рассмотрении', help_text='Введите статус заявки', max_length=200),
        ),
    ]
