# Generated by Django 4.0.2 on 2022-04-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_requestcomment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcomment',
            old_name='comment_text',
            new_name='text',
        ),
    ]
