# Generated by Django 4.0.2 on 2022-04-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0014_requestcomment_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcomment',
            name='status',
            field=models.CharField(default='Ответ', help_text='Введите статус заявки', max_length=200),
        ),
    ]
