# Generated by Django 4.0.2 on 2022-04-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_worker'),
        ('requests', '0016_request_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.worker'),
        ),
    ]
