# Generated by Django 4.0.2 on 2022-04-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0017_alter_request_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
    ]
