# Generated by Django 4.0.2 on 2022-04-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0018_rename_comment_text_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Введите комментарий длиной не более 85 символов', max_length=85),
        ),
    ]
