# Generated by Django 4.0.2 on 2022-04-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_worker'),
        ('requests', '0019_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.worker'),
        ),
    ]
