# Generated by Django 4.0.2 on 2022-04-24 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0021_alter_comment_service_alter_comment_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.CharField(default='Ваше замечание будет устранено в течении 5 дней.', max_length=85),
        ),
        migrations.AddField(
            model_name='comment',
            name='completion_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='request',
            name='answer',
            field=models.CharField(default='Ваша заявка будет выполнена в течении 5 дней.', max_length=85),
        ),
        migrations.AddField(
            model_name='request',
            name='completion_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('В обработке', 'В обработке'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена'), ('Отложена', 'Отложена'), ('Выполнена', 'Выполнена')], default='На рассмотрении', help_text='Введите статус заявки', max_length=200),
        ),
    ]
