# Generated by Django 4.0.2 on 2022-04-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0022_comment_answer_comment_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.CharField(max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='answer',
            field=models.CharField(max_length=85, null=True),
        ),
    ]
