# Generated by Django 4.0.2 on 2022-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0023_alter_comment_answer_alter_request_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='answer',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
    ]
