# Generated by Django 4.0.2 on 2022-04-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0024_alter_comment_answer_alter_request_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcomment',
            name='answer',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
    ]
