# Generated by Django 4.0.2 on 2022-05-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0027_alter_comment_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='comments', verbose_name='Фотография'),
        ),
    ]
